plots:
	#gnuplot "computeTimesLinespoints4x4.plt"
	gnuplot "computeTimesLinespoints.plt"
	gnuplot "computeTimesScatter.plt"
	gnuplot "numFacesByVerticesGoTo2.plt"
	gnuplot "outputSerialVsGPGPU.plt"

clean:
	rm -f *.png
